apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-env-gke
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MitaliV6/gcp-knative.git  # Update with your repo URL
    targetRevision: main
    path: argo-apps/dev-env
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


